name: roxsi
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - openpyxl
  - PyPDF2
  - jupyter
  - numpy
  - scipy
  - pandas
  - xarray
  - statsmodels
  - matplotlib
  - scikit-learn
  - cftime
  - cf_xarray
  - astropy
  - netcdf4
  - tqdm
