name: roxsi
channels:
  - conda-forge
dependencies:
  - python=3.9.14
  - ipython
  - pip
  - ipympl
  - utm
  - openpyxl
  - PyPDF2
  - jupyter
  - numpy
  - scipy
  - pandas
  - geopandas=0.11.1
  - xarray
  - pint-xarray
  - pint
  - statsmodels
  - matplotlib
  - cmocean
  - cmcrameri
  - motionless
  - salem
  - shapely
  - scikit-learn
  - scikit-image
  - nbconvert
  - dolfyn
  - cftime
  - cf_xarray
  - astropy
  - eofs
  - netcdf4
  - h5netcdf
  - tqdm
